### ISSUE TITLE
Dissappearing Ghosts

### ISSUE THREAD

**Issue by CyberRagz** [SLFaleiro/MMM-Halloween#2]
A very good project and in time for Halloween. The issue is that the ghosts appear on startup of the MM but then dissappear.  What is significance of update interval. Is random appearance design feature? Can he colours of the ghosts be changed to other colours? Can the ghosts be made to appear in multiple pages of the same MM instance? Thanks

**Comment by CyberRagz** [comment]
Issue can be closed. The update interval was set very high as i copied the config.js code with the existing interval. I reduced it to 10 seconds. Also i added the module in each page where it was to be shown., so it shows up in multiple pages.

**Comment by SLFaleiro** [comment]
_Is random appearance design feature?_
Yes, random appearance is a fitting design feature for ghosts.
 
 _Can the colours of the ghosts be changed to other colours?_
 You can edit or change the image located in MMM-Halloween\assets\images\ghost.png
